version: 2
jobs:
  build:
    working_directory: ~/workspace

    docker:
      - image: docker:18.03-git

    steps:
      - checkout
      - setup_remote_docker
      - run:
          command: docker build -t moyomot/neologd-igo:1 .

      - deploy:
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              docker login -u "$DOCKER_HUB_USER" -p "$DOCKER_HUB_PASSWORD"
              docker push moyomot/neologd-igo:1
            fi

scheduled-workflow:
    triggers:
      - schedule:
          cron: "47 * * * *"
          filters:
            branches:
              only: master

    jobs:
      - build
