version: 2
    
jobs:   
  build:
    working_directory: ~/workspace        
    docker:
      - image: docker:18.03-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          command: |
            docker build -t moyomot/neologd-igo .
      - deploy:
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              export TAG=`date +%Y.%m.%d`
              docker login -u "$DOCKER_HUB_USER" -p "$DOCKER_HUB_PASSWORD"
              docker tag moyomot/neologd-igo:"$TAG"
              docker push moyomot/neologd-igo:"$TAG"
              docker tag moyomot/neologd-igo:latest
              docker push moyomot/neologd-igo:latest
            fi
            

